/* level 1
 * meant to be easiest level
 */
var level1 = function(){
    this.name = "Level 1";
    this.difficulty = 5;

    this.tilemap = [
        "wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
        "w                                                w",
        "w p                                              w",
        "w                                                w",
        "w                                                w",
        "w     wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww      w",
        "w     w                                   w      w",
        "w     w                                   w      w",
        "w     w                                   w      w",
        "w                                                w",
        "w                                                w",
        "w                                                w",
        "w                                                w",
        "w     w                                   w      w",
        "w     w                                   w      w",
        "w     w                                   w      w",
        "w     wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww      w",
        "w                                                w",
        "w                                                w",
        "w                                                w",
        "w                                                w",
        "w                                                w",
        "w                                                w",
        "w                                                w",
        "w                                                w",
        "w                                                w",
        "w                                                w",
        "w                                                w",
        "wwwwwww      wwwwwww                             w",
        "w                  w                             w",
        "w                  w                             w",
        "w                  w                             w",
        "w                  w                             w",
        "w                  w                             w",
        "w                  w                             w",
        "wwwwwwwwwwwwwwwwwwww          wwwwwwwwwwwwwwwwwwww",
        "w                             w                  w",
        "w                             w                  w",
        "w                             w                  w",
        "w                                                w",
        "w                                                w",
        "w                                                w",
        "w                                                w",
        "w     wwwwwwwwwwwwwwwww       w                  w",
        "w                             w                  w",
        "w                             w                  w",
        "w                             w                  w",
        "w                             w                  w",
        "w                             w                  w",
        "wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww"
        ];
};